name: benchmark1
author: author1
apiVersion: v1alpha1
stages:
  - name: candidate
    kind: candidate
    volumes:
      - volume: training
        path: /input
        readonly: true
  - name: scoring
    kind: container
    image: benchmark-image
    volumes:
      - volume: reference
        path: /reference
        readonly: true
