apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.runs.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-creator
  namespace: {{ .Values.runs.namespace }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow
  namespace: {{ .Values.runs.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-binding
  namespace: {{ .Values.runs.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-role
subjects:
- kind: ServiceAccount
  name: argo
  namespace: {{ .Values.argoController.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server-binding
  namespace: {{ .Values.runs.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-server-role
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: {{ .Values.argoController.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runs-default-workflow
  namespace: {{ .Values.runs.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.runs.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-binding
  namespace: {{ .Values.runs.namespace }}
subjects:
- kind: ServiceAccount
  name: worker
  namespace: worker
roleRef:
  kind: Role
  name: workflow-creator
  apiGroup: rbac.authorization.k8s.io
---
{{- if and .Values.identities.benchmark.tenantId .Values.identities.benchmark.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: benchmark-identity-sp
  namespace: {{ .Values.runs.namespace }}
data:
  clientSecret: {{ .Values.identities.benchmark.clientSecret | b64enc }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: benchmark
  namespace: {{ .Values.runs.namespace }}
spec:
  type: 1
  tenantID: {{ .Values.identities.benchmark.tenantId }}
  clientID: {{ .Values.identities.benchmark.clientId }}
  clientPassword:
    name: benchmark-identity-sp
---
{{- else }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: benchmark
  namespace: {{ .Values.runs.namespace }}
spec:
  azureIdentity: benchmark
  selector: benchmark
---
# TODO: wire SP to containers during dev
---
{{- end }}
{{- if and .Values.identities.candidate.tenantId .Values.identities.candidate.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: candidate-identity-sp
  namespace: {{ .Values.runs.namespace }}
data:
  clientSecret: {{ .Values.identities.candidate.clientSecret | b64enc }}
---
# TODO: wire SP to containers during dev
---
{{- else }}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: candidate
  namespace: {{ .Values.runs.namespace }}
spec:
  azureIdentity: candidate
  selector: candidate
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: candidate
  namespace: {{ .Values.runs.namespace }}
spec:
  type: 0
  resourceID: {{ .Values.identities.candidate.resourceId }}
  clientID: {{ .Values.identities.candidate.clientId }}
---
{{- end }}
