apiVersion: v1
kind: Namespace
metadata:
  name: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        aadpodidbinding: worker
    spec:
      serviceAccountName: worker
      containers:
      - name: worker
        image: {{ .Values.worker.image }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: QUEUE_MODE
          value: {{ .Values.worker.queueMode }}
        - name: QUEUE_ENDPOINT
          value: {{ .Values.worker.queueEndpoint }}
        {{- if .Values.worker.tenantId }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.worker.tenantId }}
        {{- end }}
        {{- if .Values.worker.clientId }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.worker.clientId }}
        {{- end }}
        {{- if .Values.worker.clientSecret }}
        - name: AZURE_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: sds-worker-sp
                key: clientSecret
        {{- end }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: worker
  namespace: worker
spec:
  type: 0
  resourceID: {{ .Values.workerIdentity.resourceId }}
  clientID: {{ .Values.workerIdentity.clientId }}
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: worker
  namespace: worker
spec:
  azureIdentity: worker
  selector: worker
---
