apiVersion: v1
kind: Namespace
metadata:
  name: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: worker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-binding
  namespace: runs
subjects:
- kind: ServiceAccount
  name: worker
  namespace: worker
roleRef:
  kind: Role
  name: workflow-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: worker
      containers:
      - name: worker
        image: acanthamoeba/sds-worker
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        env:
        - name: QUEUE_MODE
          value: azure
        - name: QUEUE_ENDPOINT
          value: https://myaccount.queue.core.windows.net/runs
